name: Test

on: [push, status]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        export PYTHONPATH=.
        coverage run -m pytest --junitxml=JUnit.xml
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
